version: '3.3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  development:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: ..
      dockerfile: Dockerfile

    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../src:/home/vscode/src
      - ../.bash_history:/root/.bash_history
      - ../.zsh_history:/root/.zsh_history

    env_file:
      - .devcontainer.env
      - ../42header.env

    ports:
      - '2222:22'

volumes:
  debug:
    driver: local
